from typing import List, Tuple
from pydantic import BaseModel, Field

class TextChunk(BaseModel):
    text: str = Field(..., alias="chunk", description="The chunked text content.")
    line_span: Tuple[int, int] = Field(
        ...,
        description="Inclusive 1-based (start_line, end_line) in the source file.",
        examples=[(12, 24)],
    )
    source_file: str = Field(
        ...,
        description="Path to the file from which the chunk was extracted.",
    )
    pull_request_number: str = Field(
        ...,
        description="The pull request number",
    )
    repo: str = Field(
        ...,
        description="The name of the repository",
    )
    repo_owner: str = Field(
        ...,
        description="The owner of the repository",
    )
    def compare(self, other: "TextChunk") -> bool:
        """Compare two SecretsDetectorAgentMemory objects by source_file and line_span."""
        return (
            self.source_file == other.source_file
            and self.line_span == other.line_span
        )

class PRFileInfo(BaseModel):
    source_file: str = Field(
        ...,
        description="FULL Path to the file.",
    )
    pull_request_number: str = Field(
        ...,
        description="The pull request number",
    )
    source_branch: str = Field(
        ...,
        description="The source branch of the pull request",
    )
    repo: str = Field(
        ...,
        description="The name of the repository",
    )
    repo_owner: str = Field(
        ...,
        description="The owner of the repository",
    )

class PRFileList(BaseModel):
    files: List[PRFileInfo] = Field(
        default_factory=list,
        description="List of files in the pull request.",
    )

class LineComment(BaseModel):
    line_number: int = Field(..., description="Line number in the file (1-based).")
    comment: str = Field(..., description="Reviewer comment for this line.")

class SecretsDetectorExecutorResponse(BaseModel):
    comments: List[LineComment] = Field(
        default_factory=list,
        description="All line-level comments generated by the detector.",
    )
    original_file: str = Field(
        ...,
        alias="original_file",
        description="Path to the original file that was scanned.",
    )
    executor_agent: str = Field(
        default="No agent",
        description="The id of the executor agent who processed this request",
    )
    pull_request_number: str = Field(
        ...,
        description="The pull request number",
    )
    repo: str = Field(
        ...,
        description="The name of the repository",
    )
    repo_owner: str = Field(
        ...,
        description="The owner of the repository",
    )
    def is_empty(self) -> bool:
        return (not self.comments) and (self.original_file == "") and (self.executor_agent == "")

class EmptySecretsDetectorExecutorResponseFactory(SecretsDetectorExecutorResponse):
    @staticmethod
    def get_empty_secrets_detector():
        return SecretsDetectorExecutorResponse(comments=[], original_file="", executor_agent="", repo="", repo_owner="", pull_request_number="")

